var GoogleMapsAPI = require('googlemaps');
var ejs = require("ejs");
var fs = require('graceful-fs');

var records = require('./unitedstates.js')

var publicConfig = {
    key: 'AIzaSyBo-tnlA0XQvTzmXtRP9CESF5H--KuzgK4',
    stagger_time: 1000, // for elevationPath
    encode_polylines: false,
    secure: true, // use https
};

var gmAPI = new GoogleMapsAPI(publicConfig);

// connecting to Mongodb database running instance
var MongoClient = require('mongodb').MongoClient;
var assert = require('assert');
var ObjectId = require('mongodb').ObjectID;

// connect to the flights database in mongodb
var mongourl = 'mongodb://localhost:27017/flights';

var citiesToLoc = {};

records.cities1000Map.forEach(function (d) {

    var c = d["city"];
    c = c.replace(", USA", "");
    var loc = d["ll"].split(",");
    citiesToLoc[c] = [parseFloat(loc[0]), parseFloat(loc[1])];
});

var cache = "";

var cities = [
 "Manhattan, KS",
 "Eugene, OR",
 "Medford, OR",
 "Seattle, WA",
 "Portland, OR",
 "Klamath Falls, OR",
 "San Francisco, CA",
 "Los Angeles, CA",
 "Wenatchee, WA",
 "Yakima, WA",
 "Elko, NV",
 "Salem, OR",
 "Spokane, WA",
 "Redding, CA",
 "Lewiston, ID",
 "Astoria, OR",
 "Port Angeles, WA",
 "Pendleton, OR",
 "San Jose, CA",
 "Eureka, CA",
 "Pullman, WA",
 "Sacramento, CA",
 "Fort Lauderdale, FL",
 "Phoenix, AZ",
 "Longview, TX",
 "Great Falls, MT",
 "Fresno, CA",
 "Tucson, AZ",
 "Moses Lake, WA",
 "Billings, MT",
 "Dallas, TX",
 "Roseburg, OR",
 "Salt Lake City, UT",
 "Casper, WY",
 "Bend, OR",
 "Reno, NV",
 "Fairbanks, AK",
 "Anchorage, AK",
 "El Paso, TX",
 "Chico, CA",
 "Santa Fe, NM",
 "Albuquerque, NM",
 "Fort Smith, AR",
 "Las Vegas, NV",
 "Wichita, KS",
 "Duluth, MN",
 "Crescent City, CA",
 "Oklahoma City, OK",
 "San Diego, CA",
 "Santa Rosa, CA",
 "Durango, CO",
 "Oakland, CA",
 "Houston, TX",
 "Dubuque, IA",
 "Helena, MT",
 "Tulsa, OK",
 "Omaha, NE",
 "Waco, TX",
 "Butte, MT",
 "Austin, TX",
 "Peoria, IL",
 "Wausau, WI",
 "Pueblo, CO",
 "Topeka, KS",
 "Colorado Springs, CO",
 "Grand Junction, CO",
 "North Platte, NE",
 "Wichita Falls, TX",
 "Cheyenne, WY",
 "Aberdeen, SD",
 "Brainerd, MN",
 "Amarillo, TX",
 "Roswell, NM",
 "Bismarck, ND",
 "Missoula, MT",
 "Gillette, WY",
 "Lubbock, TX",
 "Liberal, KS",
 "Midland, TX",
 "Madison, WI",
 "Lincoln, NE",
 "Waterloo, IA",
 "Rockford, IL",
 "Green Bay, WI",
 "La Crosse, WI",
 "Kalispell, MT",
 "Milwaukee, WI",
 "Bellingham, WA",
 "Fort Dodge, IA",
 "Des Moines, IA",
 "Eau Claire, WI",
 "Mason City, IA",
 "Rapid City, SD",
 "Little Rock, AR",
 "Shreveport, LA",
 "Kansas City, MO",
 "Grand Forks, ND",
 "Bakersfield, CA",
 "San Antonio, TX",
 "Minneapolis, MN",
 "Springfield, MO",
 "Scottsbluff, NE",
 "Sioux Falls, SD",
 "Grand Island, NE",
 "Cedar Rapids, IA",
 "Fayetteville, AR",
 "Sioux City, IA",
 "Garden City, KS",
 "Baton Rouge, LA",
 "Idaho Falls, ID",
 "Springfield, IL",
 "Santa Barbara, CA",
 "Corpus Christi, TX",
 "Decatur, IL",
 "Chicago, IL",
 "Bozeman, MT",
 "Pierre, SD",
 "Monroe, LA",
 "Yuma, AZ",
 "Minot, ND",
 "Gary, IN",
 "Fargo, ND",
 "Rochester, MN",
 "St. Louis, MO",
 "Nashville, TN",
 "Evansville, IN",
 "Memphis, TN",
 "Jackson, MS",
 "Modesto, CA",
 "Champaign, IL",
 "Stockton, CA",
 "Indianapolis, IN",
 "Bloomington, IL",
 "Twin Falls, ID",
 "Laredo, TX",
 "Akron, OH",
 "Montrose, CO",
 "Cleveland, OH",
 "College Station, TX",
 "Detroit, MI",
 "Abilene, TX",
 "Dayton, OH",
 "Cincinnati, OH",
 "Jackson, WY",
 "Columbus, OH",
 "South Bend, IN",
 "Fort Wayne, IN",
 "Kalamazoo, MI",
 "Rock Springs, WY",
 "Beaumont, TX",
 "Pocatello, ID",
 "Salina, KS",
 "Quincy, IL",
 "Lawton, OK",
 "Toledo, OH",
 "Riverton, WY",
 "Brownsville, TX",
 "San Angelo, TX",
 "San Luis Obispo, CA",
 "Sheridan, WY",
 "Merced, CA",
 "Killeen, TX",
 "Cedar City, UT",
 "Ponca City, OK",
 "Harrison, AR",
 "Enid, OK",
 "Brownwood, TX",
 "Dodge City, KS",
 "Pittsburgh, PA",
 "Worcester, MA",
 "Ithaca, NY",
 "Elmira, NY",
 "Boston, MA",
 "Atlanta, GA",
 "Philadelphia, PA",
 "Greensboro, NC",
 "Flint, MI",
 "Buffalo, NY",
 "Newark, NJ",
 "Bangor, ME",
 "Charlotte, NC",
 "New York, NY",
 "Syracuse, NY",
 "Richmond, VA",
 "Grand Rapids, MI",
 "Allentown, PA",
 "Providence, RI",
 "Lexington, KY",
 "Birmingham, AL",
 "Atlantic City, NJ",
 "Orlando, FL",
 "Youngstown, OH",
 "Portland, ME",
 "Harrisburg, PA",
 "Binghamton, NY",
 "Washington, DC",
 "Albany, NY",
 "New Orleans, LA",
 "Rochester, NY",
 "Scranton, PA",
 "Roanoke, VA",
 "Raleigh, NC",
 "Greenville, SC",
 "Burlington, VT",
 "Charleston, WV",
 "Charleston, SC",
 "Chattanooga, TN",
 "State College, PA",
 "Charlottesville, VA",
 "Lansing, MI",
 "Hartford, CT",
 "Columbia, SC",
 "Jamestown, NY",
 "Manchester, NH",
 "Wilmington, NC",
 "Florence, SC",
 "Kinston, NC",
 "Baltimore, MD",
 "Erie, PA",
 "Greenville, NC",
 "Knoxville, TN",
 "Huntsville, AL",
 "Bowling Green, KY",
 "London, KY",
 "Winchester, VA",
 "Goldsboro, NC",
 "Myrtle Beach, SC",
 "Saginaw, MI",
 "Columbus, IN",
 "Shelbyville, TN",
 "Tallahassee, FL",
 "Bloomington, IN",
 "Marion, OH",
 "Montgomery, AL",
 "Mansfield, OH",
 "Pensacola, FL",
 "Talladega, AL",
 "Traverse City, MI",
 "Madisonville, KY",
 "Miami, FL",
 "Gulfport, MS",
 "Tuscaloosa, AL",
 "Del Rio, TX",
 "Alexandria, LA",
 "Terre Haute, IN",
 "Rocky Mount, NC",
 "Tampa, FL",
 "Santa Ana, CA",
 "Great Bend, KS",
 "Kearney, NE",
 "Burlington, IA",
 "Joplin, MO",
 "Fort Leonard Wood, MO",
 "Honolulu, HI",
 "Kahului, HI",
 "Fallon, NV",
 "Lafayette, LA",
 "Ketchikan, AK",
 "Lake Charles, LA",
 "Wilmington, OH",
 "Mobile, AL",
 "Logan, UT",
 "Las Cruces, NM",
 "Riverside, CA",
 "Columbia, MO",
 "Tyler, TX",
 "Jacksonville, FL",
 "West Palm Beach, FL",
 "Savannah, GA",
 "Flagstaff, AZ",
 "Stillwater, OK",
 "Columbus, GA",
 "El Dorado, AR",
 "Panama City, FL",
 "Gainesville, FL",
 "Alamogordo, NM",
 "Wilmington, DE",
 "Lake Havasu City, AZ",
 "El Centro, CA",
 "Fayetteville, NC",
 "Tacoma, WA",
 "Trenton, NJ",
 "Appleton, WI",
 "Battle Creek, MI",
 "Lafayette, IN",
 "Reading, PA",
 "Muskegon, MI",
 "Hagerstown, MD",
 "Marquette, MI",
 "Utica, NY",
 "Augusta, GA",
 "Asheville, NC",
 "Valdosta, GA",
 "Dover, DE",
 "Clovis, NM",
 "Jamestown, ND",
 "Marion, IL",
 "Greenville, MS",
 "Elkhart, IN",
 "Bemidji, MN",
 "Warrensburg, MO",
 "Laramie, WY",
 "Oshkosh, WI",
 "Morristown, TN",
 "Alpena, MI",
 "Kirksville, MO",
 "Paducah, KY",
 "Columbia, TN",
 "Crossville, TN",
 "Decatur, AL",
 "Sandusky, OH",
 "Ardmore, OK",
 "Carlsbad, NM",
 "Hobbs, NM",
 "Farmington, NM",
 "Ruidoso, NM",
 "Brookings, SD",
 "Huron, SD",
 "Brunswick, GA",
 "Albany, GA",
 "Dothan, AL",
 "Jacksonville, NC",
 "Meridian, MS",
 "Columbus, MS",
 "Lynchburg, VA",
 "Macon, GA",
 "Key West, FL",
 "New Iberia, LA",
 "Naples, FL",
 "New Bern, NC",
 "Athens, GA",
 "Blytheville, AR",
 "Altus, OK",
 "Hickory, NC",
 "Clarksburg, WV",
 "Tupelo, MS",
 "Hattiesburg, MS",
 "Ocala, FL",
 "Muncie, IN",
 "Sumter, SC",
 "Johnstown, PA",
 "Anderson, SC",
 "Ogden, UT",
 "Hot Springs, AR",
 "Lakeland, FL",
 "Staunton, VA",
 "Lake City, FL",
 "Miami, OK",
 "Williston, ND",
 "Dickinson, ND",
 "Brigham City, UT",
 "St. George, UT",
 "Mountain Home, ID",
 "Norfolk, NE",
 "Albany, OR",
 "Hilo, HI",
 "Carbondale, IL",
 "Anderson, IN",
 "Springfield, OH",
 "Nogales, AZ",
 "Anniston, AL",
 "Findlay, OH",
 "Bridgeport, CT",
 "New Haven, CT",
 "Rutland, VT",
 "Ogdensburg, NY",
 "Rockland, ME",
 "Watertown, NY",
 "St. Cloud, MN",
 "Auburn, AL",
 "Plattsburgh, NY",
 "Iron Mountain, MI",
 "Provo, UT",
 "Cape Girardeau, MO",
 "Parkersburg, WV",
 "York, PA",
 "Augusta, ME",
 "Salisbury, MD",
 "Punta Gorda, FL",
 "Rexburg, ID",
 "Silver City, NM",
 "Corsicana, TX",
 "Williamsport, PA",
 "Jonesboro, AR",
 "Sterling, IL",
 "Eagle Pass, TX",
 "Watertown, SD",
 "Gadsden, AL",
 "Victoria, TX",
 "Rome, GA",
 "St. Joseph, MO",
 "Branson, MO",
 "Jackson, TN",
 "Mount Vernon, IL",
 "Holland, MI",
 "Lewiston, ME",
 "Bradford, PA",
 "Gallup, NM",
 "Ukiah, CA",
 "Oxnard, CA",
 "Visalia, CA",
 "Show Low, AZ",
 "Havre, MT",
 "Hays, KS",
 "Juneau, AK",
 "Kodiak, AK",
 "Altoona, PA",
 "Grenada, MS",
 "Houma, LA",
 "Marshall, MN",
 "Athens, TN",
 "Sturgis, MI",
 "Jefferson City, MO",
 "Searcy, AR",
 "Glasgow, KY",
 "Spartanburg, SC",
 "Dyersburg, TN",
 "Connersville, IN",
 "Seymour, IN",
 "Borger, TX",
 "Lancaster, PA",
 "Ames, IA",
 "Bend, OR",
 "Elko, NV",
 "Enid, OK",
 "Erie, PA",
 "Gary, IN",
 "Hays, KS",
 "Hilo, HI",
 "Lima, OH",
 "Napa, CA",
 "Peru, IN",
 "Reno, NV",
 "Rome, GA",
 "Taos, NM",
 "Waco, TX",
 "York, PA",
 "Yuma, AZ",
 "Akron, OH",
 "Altus, OK",
 "Butte, MT",
 "Chico, CA",
 "Dover, DE",
 "Fargo, ND",
 "Flint, MI",
 "Havre, MT",
 "Hobbs, NM",
 "Houma, LA",
 "Huron, SD",
 "Logan, UT",
 "Macon, GA",
 "Miami, FL",
 "Miami, OK",
 "Minot, ND",
 "Ocala, FL",
 "Ogden, UT",
 "Omaha, NE",
 "Paris, TN",
 "Price, UT",
 "Provo, UT",
 "Salem, OR",
 "Selma, AL",
 "Tampa, FL",
 "Tulsa, OK",
 "Tyler, TX",
 "Ukiah, CA",
 "Utica, NY",
 "Albany, GA",
 "Albany, NY",
 "Albany, OR",
 "Alpena, MI",
 "Athens, GA",
 "Athens, TN",
 "Auburn, AL",
 "Auburn, IN",
 "Austin, TX",
 "Bangor, ME",
 "Bishop, CA",
 "Boston, MA",
 "Burley, ID",
 "Casper, WY",
 "Clovis, NM",
 "Dallas, TX",
 "Dalton, GA",
 "Dayton, OH",
 "Dothan, AL",
 "Duluth, MN",
 "Easton, MD",
 "Elmira, NY",
 "Eugene, OR",
 "Eureka, CA",
 "Fallon, NV",
 "Fresno, CA",
 "Gallup, NM",
 "Helena, MT",
 "Hudson, NY",
 "Ithaca, NY",
 "Joplin, MO",
 "Juneau, AK",
 "Kodiak, AK",
 "Kokomo, IN",
 "Laredo, TX",
 "Laurel, MS",
 "Lawton, OK",
 "London, KY",
 "Madera, CA",
 "Marion, IL",
 "Marion, IN",
 "Marion, OH",
 "Merced, CA",
 "Mobile, AL",
 "Monroe, LA",
 "Muncie, IN",
 "Naples, FL",
 "Newark, NJ"
];

function sleep(milliseconds) {
    var start = new Date().getTime();
    for (var i = 0; i < 1e7; i++) {
        if ((new Date().getTime() - start) > milliseconds) {
            break;
        }
    }
}

cities.forEach(function (d) {

    if (!citiesToLoc[d]) {

        var geocodeParams = {
            "address": d,
            "language": "en",
            "region": "usa"
        };

        gmAPI.geocode(geocodeParams,

            function (err, result) {

                console.log(result);

                citiesToLoc[d] = result["results"][0].geometry.location;

                writeToFile(JSON.stringify({
                    city: d,
                    ll: [citiesToLoc[d].lat, citiesToLoc[d].lng]
                }) + "\n");

                sleep(100);
            });

    } else {

        //        writeToFile({
        //            city: d,
        //            ll: citiesToLoc[d]
        //        });

        cache = cache + JSON.stringify({
            city: d,
            ll: citiesToLoc[d]
        }) + "\n";
    }

});


writeToFile(cache);

function writeToFile(data) {
    console.log(data);

    fs.appendFile('public/data/locations.json', data,

        function (err) {
            if (err) throw err;
            console.log('userlog.csv was written');
        });
}

exports.citiesToLoc = citiesToLoc;